spring:
  application:
  name: lecture-service

  datasource:
    url: jdbc:mysql://localhost:3306/lecture
    username: root
    password: 12341234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect


logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug
