spring:
  application:
  name: lecture-service

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:lecture
    driverClassName: org.h2.Driver
    username: sa
    password:

    messages:
      basename: message
      encoding: utf-8

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.springframework.security: debug